import fs from 'node:fs';
import path from 'node:path';

const distDir = path.resolve('dist');
const requiredFiles = ['index.html', 'feed.xml', 'searchIndex.json', 'pages.json', 'graph.json', 'siteStats.json', 'sw.js'];
const maxFeedBytes = 5 * 1024 * 1024;

for (const relativePath of requiredFiles) {
  const filePath = path.join(distDir, relativePath);
  if (!fs.existsSync(filePath)) {
    const sourceHint = relativePath === 'pages.json' ? ' (generated by src/site/pages.njk — ensure that template is tracked in git)' : '';
    throw new Error(`Missing build output: ${relativePath}${sourceHint}`);
  }
}

const feed = fs.readFileSync(path.join(distDir, 'feed.xml'), 'utf8');
const feedBytes = Buffer.byteLength(feed);
if (feedBytes > maxFeedBytes) {
  throw new Error(`Feed is too large: ${feedBytes} bytes (limit ${maxFeedBytes})`);
}
if (!feed.includes('<summary type="text">') || feed.includes('<content type="html">')) {
  throw new Error('Feed must contain text summaries instead of full HTML content');
}

const stats = JSON.parse(fs.readFileSync(path.join(distDir, 'siteStats.json'), 'utf8'));
if (!Number.isInteger(stats.pageCount) || stats.pageCount <= 0) {
  throw new Error('Build statistics are missing a valid pageCount');
}

const pages = JSON.parse(fs.readFileSync(path.join(distDir, 'pages.json'), 'utf8'));
if (!Array.isArray(pages) || pages.some((page) => !page || typeof page.url !== 'string')) {
  throw new Error('Pages index must be an array of URL records');
}
if (new Set(pages.map((page) => page.url)).size !== pages.length) {
  throw new Error('Pages index contains duplicate URLs');
}

const searchIndex = JSON.parse(fs.readFileSync(path.join(distDir, 'searchIndex.json'), 'utf8'));
if (
  !Array.isArray(searchIndex) ||
  searchIndex.some(
    (entry) =>
      !entry ||
      typeof entry.url !== 'string' ||
      typeof entry.title !== 'string' ||
      typeof entry.content !== 'string' ||
      !Array.isArray(entry.tags)
  )
) {
  throw new Error('Search index entries must contain title, url, content strings and a tags array');
}
if (new Set(searchIndex.map((entry) => entry.url)).size !== searchIndex.length) {
  throw new Error('Search index contains duplicate URLs');
}

function collectHtmlFiles(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const child = path.join(directory, entry.name);
    return entry.isDirectory() ? collectHtmlFiles(child) : (entry.name.endsWith('.html') ? [child] : []);
  });
}

for (const htmlPath of collectHtmlFiles(distDir)) {
  const html = fs.readFileSync(htmlPath, 'utf8');
  if (/<h[1-6][^>]*id="[^"]*(?:<|>|\[\[)/i.test(html)) {
    throw new Error(`Invalid heading id in ${path.relative(distDir, htmlPath)}`);
  }
}

console.log(`Build verification passed: ${stats.pageCount} pages, feed ${feedBytes} bytes, random index ${pages.length} entries`);
